### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by Nosxxx** [greatman/craftconomy3#11]
I'm getting the folowing error:
http://hastebin.com/kigupotovi.avrasm
What's wrong ?

**Comment by tkausl** [comment]
The query looks okay, i guess you somehow managed to create two bank-accounts with the same name.

**Comment by Nosxxx** [comment]
I think someone changed his name and sombody else joined the server. So the 2 accounts are there.

**Comment by tkausl** [comment]
#15 should fix the exception but there is still the possibility that you withdraw from the wrong account since Vault uses the username, not the UUID to find the account.

**Comment by greatman** [comment]
Commited.
