### ISSUE TITLE
old lang.yml file cause SNAPSHOT failing on start up

### ISSUE THREAD

**Issue by PikachuEXE** [greatman/craftconomy3#18]
I was trying to get a fix for `/money log`
So I build locally (commit: dacf93cf547fef8d39fbbe54840fe10d52a356fa)
But now typing any command does not display any message

I am using a test spigot server (1.8.5 build 434 for testing)
To ensure it has got nothing to do with my server setup 
I have tried using downloaded 3.2.1 jar file, it works

I cannot build 3.2.1 for testing my build setup due to outdated dependency
```
Could not resolve org.mcstats.standalone:metrics:R7
com.greatmancode:craftconomy3:3.2.1 > com.greatmancode:tools:1.1 > net.canarymod:CanaryLib:1.2.0
Could not GET 'https://libraries.minecraft.net/org/mcstats/standalone/metrics/R7/metrics-R7.pom'. Received status code 403 from server: Forbidden
```

**Comment by greatman** [comment]
Hmm, ill check it out, i've been full Sponge mode atm so other implementations might be broken.

**Comment by PikachuEXE** [comment]
OK :S
I can't figure out what's wrong by looking at the diff of 3.2.1 & master
No error log on start up / command execution
Very strange

**Comment by greatman** [comment]
Should be fine on latest build!

**Comment by PikachuEXE** [comment]
Going to try soon (after lunch :hamburger: hehe)

**Comment by PikachuEXE** [comment]
Got exception on startup:
```
[Craftconomy3] Loading the Configuration
[13:48:44] [Server thread/ERROR]: Error occurred while enabling Craftconomy3 v3.2.2-SNAPSHOT-d67c61c-dev (Is it up to date?)
java.lang.ClassCastException: org.bukkit.configuration.MemorySection cannot be cast to java.lang.String
	at com.greatmancode.craftconomy3.tools.configuration.bukkit.BukkitConfig.getStringMap(BukkitConfig.java:113) ~[?:?]
	at com.greatmancode.craftconomy3.tools.language.LanguageManager.loadLanguage(LanguageManager.java:39) ~[?:?]
	at com.greatmancode.craftconomy3.tools.language.LanguageManager.<init>(LanguageManager.java:35) ~[?:?]
	at com.greatmancode.craftconomy3.Common.onEnable(Common.java:109) ~[?:?]
	at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:49) ~[?:?]
```

I am using config at https://raw.githubusercontent.com/greatman/craftconomy3/master/src/main/resources/config.yml

**Comment by greatman** [comment]
Delete lang.yml

**Comment by PikachuEXE** [comment]
OK it works now
One more thing to add to upgrade guide ?

**Comment by greatman** [comment]
More a thing to fix. I broke it during sponge support.

**Comment by PikachuEXE** [comment]
Title changed

**Comment by greatman** [comment]
Got a possible fix in progress, just waiting on something to get fixed so I can do my tests (Canary repo is down).

**Comment by greatman** [comment]
Fixed in the latest builds.

**Comment by PikachuEXE** [comment]
Let me test it on weekend hehe
