### ISSUE TITLE
java.sql.SQLException: Subquery returns more than 1 row

### ISSUE THREAD

**Issue by 9190281** [greatman/craftconomy3#19]
Hello CC3 developers,
whenever town upkeep is collected for towny, it doesn't collect town/nation upkeep and spews out this error.
Error: http://pastebin.com/jkpPcp6F

**Comment by greatman** [comment]
Should be fixed by this commit (so latest dev build) https://github.com/greatman/craftconomy3/commit/2ec1c7abc26b5a9e22bf449423a830d22306efe6
