### ISSUE TITLE
Defaults no /money

### ISSUE THREAD

**Issue by TheOtakuJames** [greatman/craftconomy3#31]
Players can not use /money unless they are op. I have added it to my permissions (twice) but they still can not.

This is what I have in my permissions file:  
    - Craftconomy.money.holdings
    - Craftconomy.money.help
    - Craftconomy.money.pay
    - Craftconomy.money.top
    - Craftconomy.bank.create
    - Craftconomy.bank.delete
    - Craftconomy.bank.add
    - Craftconomy.bank.remove
    - Craftconomy.bank.deposit
    - Craftconomy.bank.withdraw
    - Craftconomy.money.holdings

They can use all of them except money.holdings.

Thanks

**Comment by ampayne2** [comment]
Try craftconomy.money.balance

**Comment by greatman** [comment]
You checked the 2.X permission page. This is the 3.X page: https://github.com/greatman/craftconomy3/wiki/Permissions
