### ISSUE TITLE
My Craftconomy doesnt works!

### ISSUE THREAD

**Issue by Kreathre** [greatman/craftconomy3#32]

**Comment by Kreathre** [comment]
Uops, only Op´s can watch his money etc

**Comment by greatman** [comment]
You need to give the permission node. Check the wiki for it.

**Comment by Kreathre** [comment]
can u send me a linkn pls?^^

**Comment by greatman** [comment]
https://github.com/greatman/craftconomy3/wiki

**Comment by Kreathre** [comment]
im new in this.. i dont know  where and what i need to do .. im sorry :(
my server is rly new and we want to make a survival.. do you wanna watch ?
