### ISSUE TITLE
Error on server start causes to leave the server without memory

### ISSUE THREAD

**Issue by stefvanschie** [greatman/craftconomy3#41]
Hey,

Everything was working fine with this plugin, until I saw a weird error. I'm making plugins myself, so if it something from me please tell me. Here's the rror:
http://pastebin.com/VNS6YvXC

**Comment by greatman** [comment]
Caused by: java.lang.OutOfMemoryError: PermGen space

For some reason your PermGen got filled, what java version do you run?

**Comment by stefvanschie** [comment]
Java 7, error did not occur after I got this bug.

**Comment by greatman** [comment]
There can be issues if you don't set your PermGen Space size. It tells what to do during minecraft server launch.

**Comment by stefvanschie** [comment]
I don't think I've set that.

**Comment by stefvanschie** [comment]
Hasn't occured anymore after setting the max space size, closing this issue.
