### ISSUE TITLE
/money and all the commands only with OP permissions

### ISSUE THREAD

**Issue by Seebasti** [greatman/craftconomy3#48]
Why isn't there a version of Craftconomy or an Option where you can turn off the permissions for Craftconomy...or an Option where you can  turn off the Permission, that default Users can use the commands without OP Permissions. I have a minecraft server and we had to install PermissionEx and Essentials (doesn't worked togehter and we have no Idea how we can do it).

It would be nice if there will be an Update with these sption or an extra version.

Thanks

**Comment by MineHeads** [comment]
commands and permissions:
http://dev.bukkit.org/bukkit-plugins/craftconomy/pages/command-and-permissions-2-x/

Only /money isn't working for not OP players. So thats a stupid bug.

**Comment by MineHeads** [comment]
If you use craftconomy3 (like i do) use this permissions

https://github.com/greatman/craftconomy3/wiki/Permissions

I tested the commands and they work great. I hope i could be of a help

**Comment by Seebasti** [comment]
Sorry..no...We don't have PermissionsEX so the Plugin isn't working for not
OPs.

2015-11-05 18:48 GMT+01:00 MineHeads <notifications@github.com>:

**Comment by Seebasti** [comment]
So how do I could remove this Bug, that non OPs can do this command?


2015-11-06 15:23 GMT+01:00 Seebasti McBurger <seebasti12@gmail.com>:

**Comment by MineHeads** [comment]
http://ess.ementalo.com/viewLog.html?buildId=lastSuccessful&tab=artifacts&buildTypeId=bt10&guest=1

this is a groupmanager so you can give default player permission to use the commands. If you give me your server ip i can help you if you like that.

I also recommend you not to download the hole essentials package because I used to work with it too but it gave a lot of errors with other plugins but groupmanager should be fine!

**Comment by greatman** [comment]
http://wiki.bukkit.org/Plugin_YAML

The plugin.yml could be modified to change the default permission settings. You can set permissions's default in it.

**Comment by MineHeads** [comment]
Seebasti, if you give me your ip of the server, ill try to help you if you want that!
