### ISSUE TITLE
Error on server start. Not sure what it means?

### ISSUE THREAD

**Issue by GRRRillaNinja** [greatman/craftconomy3#58]
26.11 01:47:29 [Server] WARN SLF4J: Defaulting to no-operation (NOP) logger implementation 
26.11 01:47:29 [Server] WARN SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by greatman** [comment]
Can be safely ignored. The error is related to slf4j missing a logger plugin, I didn't include one to not increase the .jar size for nothing. The plugin still logs fine without it.

**Comment by madtomic** [comment]
Where can I get the logger plugin?
