### ISSUE TITLE
craftconomy and vault multiworld

### ISSUE THREAD

**Issue by popcorn9499** [greatman/craftconomy3#59]
It seems that craftconomy and vault dont seem to work together very well when the multiworld support is used.
Vault will only read out of the default one. 

Im running vault 1.5.6-b49
Craftconomy 3 3.3 
spigot 1.8.8 R0.1 snapshot

This has been tested with ezrankslite

If you need something else just tell me

**Comment by greatman** [comment]
Vault multiworld needs the world given by the plugin using it. Since ezrankslite seems like a paid? plugin, I can't check it's source code to confirm if it gives the world to Vault or not. If it doesn't give the world to vault, I unfortunately default to the default world.

**Comment by popcorn9499** [comment]
i understand thanks for telling me what u can do :)

**Comment by popcorn9499** [comment]
and the version of the plugin im using is a free version off of bukkit but idk if the github still has anything. Just remember that
