### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by Pet0203** [greatman/craftconomy3#61]
Hello there! I have 4 servers with 3 different currencies, how can I fix so that each of the servers have their own currency as the default one so that they aren't set for all 4. For example: I have a hub, Towny, Factions and mini-games server. And I want different currencies on all but the hub. I want so that the players can exchange the currencies at the hub. Is this possible to fix?

**Comment by greatman** [comment]
Unfortunately right now it is impossible to have a specific default currency per server since Craftconomy is not really "server aware". It only allows multiple servers to pull from the same database.
