### ISSUE TITLE
Setting up Craftconomy for MySQL

### ISSUE THREAD

**Issue by Obris0492** [greatman/craftconomy3#62]
Hi,

I just came across Cc3 and I can't get it to work with my MySQL database. I tried using the /ccsetup command but after setting the prefix, it gives me an error. I've tried setting it in the configuration file with no luck. It does work with a flatfile but that's not what I want. I'd very much like to use this plugin for my server, so any help would be appreciated.

Kind regards,

Obris

**Comment by Obris0492** [comment]
Ok, I've fixed it. For some reason I couldn't use localhost as the host even though it's on the same computer.

**Comment by tkausl** [comment]
`it gives me an error`
