### ISSUE TITLE
Plugin is not PlugMan-Compatible

### ISSUE THREAD

**Issue by Lactem** [greatman/craftconomy3#66]
It would be very helpful if CraftConomy3 could be reloaded with PlugMan (via /plugman reload CraftConomy3). I've tried, but the plugin fails to load again with the error message: "Plugin already initialized." As you probably know, this usually happens due to incorrect use of statics or references to the loaded plugin that don't get changed when it reloads.

**Comment by greatman** [comment]
I have a command called /craftconomy reload, it should do the job you want.
