### ISSUE TITLE
CraftConomy can't connect to database.

### ISSUE THREAD

**Issue by iKaneki-Ken** [greatman/craftconomy3#78]
This is the error I get when I finish the database setup.

http://pastebin.com/v02nv1PC

**Comment by greatman** [comment]
Somehow unable to load JavaAssist, can you try the version here? JavaAssist is removed. https://oss.sonatype.org/content/repositories/snapshots/com/greatmancode/craftconomy3/3.3.1-SNAPSHOT/craftconomy3-3.3.1-20160119.021100-12.jar

**Comment by iKaneki-Ken** [comment]
Works perfectly!
