### ISSUE TITLE
1.9 Support

### ISSUE THREAD

**Issue by TheChampTF** [greatman/craftconomy3#86]
Hey

As stated in https://github.com/MassiveCraft/Factions/issues/1045 I should bring this issue to you.

**Comment by greatman** [comment]
I null at this line in Vault: https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_Craftconomy3.java#L254

Which means Craftconomy didn't start properly, any error during startup?

**Comment by TheChampTF** [comment]
That was all I did get

**Comment by CKGAR** [comment]
Is there any update on this? Multiple people have had problems with 1.9 using Vault and other plugins that use economy features.

**Comment by silverforte** [comment]
Yep, seems broken with 1.9. Really hanging in there for an update soon. Most of my server's plugins require craftconomy.

**Comment by greatman** [comment]
There's absolutly no other stacktrace of Vault/Craftconomy during startup? Because according to Vault code where it broke, it means something happened during startup or Craftconomy didn't start properly. You guys have latest Vault?

**Comment by TheChampTF** [comment]
Yea on latest vault

**Comment by greatman** [comment]
Without any kind of logs (Startup?) I can't help you, I just installed a fresh spigot 1.9 with Vault/Factions/CC3 and everything went great.

> [22:39:20] [Server thread/INFO]: Starting minecraft server version 1.9
> [22:39:20] [Server thread/INFO]: Loading properties
> [22:39:20] [Server thread/INFO]: Default game type: SURVIVAL
> [22:39:20] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-5d4e372-9554894 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
> [22:39:20] [Server thread/INFO]: Debug logging is disabled
> [22:39:20] [Server thread/INFO]: Using 4 threads for Netty based IO
> [22:39:20] [Server thread/INFO]: Server Ping Player Sample Count: 12
> [22:39:20] [Server thread/INFO]: Generating keypair
> [22:39:20] [Server thread/INFO]: Starting Minecraft server on *:25565
> [22:39:20] [Server thread/INFO]: Using default channel type
> [22:39:20] [Server thread/INFO]: Set PluginClassLoader as parallel capable
> [22:39:20] [Server thread/INFO]: [Craftconomy3] Loading Craftconomy3 v3.3.1-SNAPSHOT-4e4a8a7-trv196
> [22:39:20] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
> [22:39:20] [Server thread/INFO]: [MassiveCore] Loading MassiveCore v2.8.7Beta
> [22:39:20] [Server thread/INFO]: TimeUnit.MILLIS_PER_MINUTE: 60000
> [22:39:20] [Server thread/INFO]: [Factions] Loading Factions v2.8.7Beta
> [22:39:20] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
> [22:39:20] [Server thread/INFO]: [Vault] [Economy] CraftConomy3 found: Waiting
> [22:39:20] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
> [22:39:20] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
> [22:39:20] [Server thread/INFO]: [MassiveCore] Enabling MassiveCore v2.8.7Beta
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m=== ENABLE START ===[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;33;1mLoading Cachefile datas...[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;33;1mLoading Onlineplayer datas...[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;33;1mLoading Registry datas...[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;33;1mSaving Cachefile...[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;33;1mSetup of IdUtil took [0;35;1m10[0;33;1mms.[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;32;1mActivated Integration [0;35;1mIntegrationVault[m
> [22:39:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m111ms[0;33;1m) ===[m
> [22:39:20] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
> [22:39:20] [Server thread/INFO]: Preparing level "world"
> [22:39:20] [Server thread/INFO]: -------- World Settings For [world] --------
> [22:39:20] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
> [22:39:20] [Server thread/INFO]: Mob Spawn Range: 4
> [22:39:20] [Server thread/INFO]: Cactus Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Cane Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Melon Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Mushroom Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Sapling Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Wheat Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: NetherWart Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
> [22:39:20] [Server thread/INFO]: Random Lighting Updates: false
> [22:39:20] [Server thread/INFO]: Structure Info Saving: true
> [22:39:20] [Server thread/INFO]: Max TNT Explosions: 100
> [22:39:20] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
> [22:39:20] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
> [22:39:20] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
> [22:39:20] [Server thread/INFO]: Experience Merge Radius: 3.0
> [22:39:20] [Server thread/INFO]: Arrow Despawn Rate: 1200
> [22:39:20] [Server thread/INFO]: Item Merge Radius: 2.5
> [22:39:20] [Server thread/INFO]: Item Despawn Rate: 6000
> [22:39:20] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
> [22:39:20] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
> [22:39:20] [Server thread/INFO]: Max Entity Collisions: 8
> [22:39:20] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
> [22:39:20] [Server thread/INFO]: View Distance: 10
> [22:39:20] [Server thread/INFO]: -------- World Settings For [world_nether] --------
> [22:39:20] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
> [22:39:20] [Server thread/INFO]: Mob Spawn Range: 4
> [22:39:20] [Server thread/INFO]: Cactus Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Cane Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Melon Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Mushroom Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Sapling Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Wheat Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: NetherWart Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
> [22:39:20] [Server thread/INFO]: Random Lighting Updates: false
> [22:39:20] [Server thread/INFO]: Structure Info Saving: true
> [22:39:20] [Server thread/INFO]: Max TNT Explosions: 100
> [22:39:20] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
> [22:39:20] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
> [22:39:20] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
> [22:39:20] [Server thread/INFO]: Experience Merge Radius: 3.0
> [22:39:20] [Server thread/INFO]: Arrow Despawn Rate: 1200
> [22:39:20] [Server thread/INFO]: Item Merge Radius: 2.5
> [22:39:20] [Server thread/INFO]: Item Despawn Rate: 6000
> [22:39:20] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
> [22:39:20] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
> [22:39:20] [Server thread/INFO]: Max Entity Collisions: 8
> [22:39:20] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
> [22:39:20] [Server thread/INFO]: View Distance: 10
> [22:39:20] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
> [22:39:20] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
> [22:39:20] [Server thread/INFO]: Mob Spawn Range: 4
> [22:39:20] [Server thread/INFO]: Cactus Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Cane Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Melon Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Mushroom Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Sapling Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Wheat Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: NetherWart Growth Modifier: 100%
> [22:39:20] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
> [22:39:20] [Server thread/INFO]: Random Lighting Updates: false
> [22:39:20] [Server thread/INFO]: Structure Info Saving: true
> [22:39:20] [Server thread/INFO]: Max TNT Explosions: 100
> [22:39:20] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
> [22:39:20] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
> [22:39:20] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
> [22:39:20] [Server thread/INFO]: Experience Merge Radius: 3.0
> [22:39:20] [Server thread/INFO]: Arrow Despawn Rate: 1200
> [22:39:20] [Server thread/INFO]: Item Merge Radius: 2.5
> [22:39:20] [Server thread/INFO]: Item Despawn Rate: 6000
> [22:39:20] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
> [22:39:20] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
> [22:39:20] [Server thread/INFO]: Max Entity Collisions: 8
> [22:39:20] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
> [22:39:20] [Server thread/INFO]: View Distance: 10
> [22:39:21] [Server thread/INFO]: Preparing start region for level 0 (Seed: -7600399364534805342)
> [22:39:22] [Server thread/INFO]: Preparing spawn area: 88%
> [22:39:22] [Server thread/INFO]: Preparing start region for level 1 (Seed: -7600399364534805342)
> [22:39:22] [Server thread/INFO]: Preparing start region for level 2 (Seed: -7600399364534805342)
> [22:39:22] [Server thread/INFO]: [Craftconomy3] Enabling Craftconomy3 v3.3.1-SNAPSHOT-4e4a8a7-trv196
> [22:39:22] [Server thread/INFO]: [Craftconomy3] Starting up!
> [22:39:22] [Server thread/INFO]: [Craftconomy3] Loading the Configuration
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading listeners.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading commands
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading the Database Manager
> [22:39:23] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> [22:39:23] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
> [22:39:23] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Database Manager Loaded!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading the Currency manager.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Currency Manager Loaded!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading the Account Manager
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Starting Metrics.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Account Manager Loaded!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] World Group Manager loaded!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Quick-Config done!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Starting up!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading the Configuration
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Your database is out of date! (Version 0). Updating it to Revision 1.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Updated to Revision 1!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading default settings.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Default settings loaded!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Loading the Account Manager
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Starting Metrics.
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Account Manager Loaded!
> [22:39:23] [Server thread/INFO]: [Craftconomy3] Ready!
> [22:39:23] [Server thread/INFO]: [Vault][Economy] Craftconomy3 hooked.
> [22:39:23] [Server thread/INFO]: [Factions] Enabling Factions v2.8.7Beta
> [22:39:23] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1m=== ENABLE START ===[m
> [22:39:23] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1m[0;32;1mActivated Integration [0;35;1mIntegrationSpigot[m
> [22:39:23] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m101ms[0;33;1m) ===[m
> [22:39:23] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m101ms[0;33;1m) ===[m
> [22:39:23] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
> [22:39:23] [Server thread/INFO]: Done (2.830s)! For help, type "help" or "?"
> [22:39:23] [Craft Scheduler Thread - 3/INFO]: [Vault] Checking for Updates ... 
> [22:39:23] [Craft Scheduler Thread - 3/INFO]: [Vault] No new version available
> [22:39:39] [Server thread/INFO]: Opped greatman321
> [22:40:12] [User Authenticator #1/INFO]: UUID of player greatman321 is c8280962-04f2-4558-8f14-298b9fb090c4
> [22:40:12] [Server thread/INFO]: greatman321[/127.0.0.1:51501] logged in with entity id 211 at ([world]-159.5, 70.0, 143.5)
> [22:40:17] [Server thread/INFO]: greatman321 issued server command: /f
> [22:40:18] [Server thread/INFO]: greatman321 issued server command: /f new
> [22:40:21] [Server thread/INFO]: greatman321 issued server command: /f create test
> [22:40:21] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1m[0;33;1msetFactionId moved [0;35;1mc8280962-04f2-4558-8f14-298b9fb090c4 [0;33;1maka [0;35;1m[0;37;1mgreatman321 [0;33;1mfrom [0;35;1mnone [0;33;1maka [0;35;1m[0;32;22mWilderness [0;33;1mto [0;35;1m1ca5564c-b6eb-4fcd-b767-6f4c3aaac2ae [0;33;1maka [0;35;1mtest[0;33;1m.[m
> [22:40:21] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1mgreatman321 created a new faction: test[m
> [22:40:28] [Server thread/INFO]: greatman321 issued server command: /money
> [22:40:32] [Server thread/INFO]: greatman321 issued server command: /Money set greatman321 300
> [22:40:36] [Server thread/INFO]: greatman321 issued server command: /f bank
> [22:40:39] [Server thread/INFO]: greatman321 issued server command: /f help
> [22:40:44] [Server thread/INFO]: greatman321 issued server command: /f help 2
> [22:40:46] [Server thread/INFO]: greatman321 issued server command: /f help 3
> [22:40:53] [Server thread/INFO]: greatman321 issued server command: /f money
> [22:40:55] [Server thread/INFO]: greatman321 issued server command: /money
> [22:40:58] [Server thread/INFO]: greatman321 issued server command: /f money deposit 300
> [22:40:58] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1mgreatman321 deposited 300 Dollars 00 Coin in the faction bank: test[m
> [22:40:59] [Server thread/INFO]: greatman321 issued server command: /Money
> [22:42:28] [Server thread/INFO]: Stopping the server
> [22:42:28] [Server thread/INFO]: Stopping server
> [22:42:28] [Server thread/INFO]: [Factions] Disabling Factions v2.8.7Beta
> [22:42:28] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1m[0;31;1mDeactivated Integration [0;35;1mIntegrationSpigot[m
> [22:42:28] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.7Beta[0;36;22m] [0;33;1mDisabled[m
> [22:42:28] [Server thread/INFO]: [MassiveCore] Disabling MassiveCore v2.8.7Beta
> [22:42:28] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;31;1mDeactivated Integration [0;35;1mIntegrationVault[m
> [22:42:28] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1mDisabled[m
> [22:42:28] [Server thread/INFO]: [Vault] Disabling Vault v1.5.6-b49
> [22:42:28] [Server thread/INFO]: [Craftconomy3] Disabling Craftconomy3 v3.3.1-SNAPSHOT-4e4a8a7-trv196
> [22:42:28] [Server thread/INFO]: [Craftconomy3] Closing the connection to the database.
> [22:42:28] [Server thread/INFO]: Saving players
> [22:42:28] [Server thread/INFO]: greatman321 lost connection: Server closed
> [22:42:28] [Server thread/INFO]: greatman321 left the game.
> [22:42:28] [Server thread/INFO]: Saving worlds
> [22:42:28] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
> [22:42:29] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
> [22:42:29] [Server thread/INFO]: Saving chunks for level 'world_the_end'/The End


![2016-03-25_22 41 08](https://cloud.githubusercontent.com/assets/95754/14057589/d4400dc4-f2da-11e5-9996-5c32e2c63938.png)
